### ISSUE TITLE
This is Great! Food for thought...

### ISSUE THREAD

**Issue by zamanq** [rmorse/multiple-blocks-plugin#2]
Hi @rmorse,
Thank you for sharing a great alternative to building multiple blocks using the create-block WP Script. Everything seems fine; however, I was wondering if it's possible to combine the scripts in package.json file for all the blocks. For example, if I have 20 blocks in a plugin then I'll have to write 20 separate scrips for the start and build process which is not ideal. If I have more blocks then the list will go up. Is it possible to bring everything under one script which when runs will compile all the blocks at once?

Looking forward to hearing from you.

Best,
Zaman

**Comment by rmorse** [comment]
Hey Zaman

I think there would be a way to execute multiple scripts from one command (so we can run them all at once) - but I'm holding off on that for minute because it looks like this might be natively supported soon -

https://github.com/WordPress/gutenberg/issues/25188

The thread goes way back but it looks like there has been some forward motion recently...

I'll likely wait to see how this plays out over the next month or so, and if it doesn't look like its coming I'll do some research and find an easier way of executing those various scripts as one

**Comment by zamanq** [comment]
Hi @rmorse,
Thank you, yes let's wait a bit for the official announcement and if it's not gonna be available anytime soon then I believe you'll be figuring out an effective solution. 

Really appreciate your contribution in this regard.

Best,
